language: node_js

node_js:
    - 9.3.0

npm:
    - 5.6.0

cache:
  directories:
    - node_modules

install:
    npm install

script:
    - npm run build
    - npm run test -- --maxWorkers=2
    - npm run lint

notifications:
  email: false
